# Generated by Django 3.0.5 on 2020-04-22 23:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appeals', '0005_auto_20200419_2223'),
        ('accounts', '0014_auto_20200413_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appeals.Appeal')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Org')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.User')),
            ],
        ),
    ]
