# Generated by Django 3.0.5 on 2020-04-25 14:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200413_1609'),
        ('appeals', '0005_auto_20200419_2223'),
        ('payments', '0002_auto_20200423_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('street_address1', models.CharField(max_length=100)),
                ('street_address2', models.CharField(blank=True, max_length=100)),
                ('town_or_city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=40)),
                ('postcode', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('anonymous', models.BooleanField(default=False)),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appeals.Appeal')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Org')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
