# Generated by Django 3.0.5 on 2020-04-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20200425_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='successful',
            field=models.BooleanField(default=False),
        ),
    ]
