# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-08 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200308_2024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
