# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-10 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200310_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=200)),
                ('org_type', models.CharField(choices=[('bug', 'Registered Charity'), ('feature', 'Community Project')], default='bug', max_length=7)),
                ('bio', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.User')),
            ],
        ),
    ]
