# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-10 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='org_type',
            field=models.CharField(choices=[('Registered Charity', 'Registered Charity'), ('Community Project', 'Community Project')], default='Registered Charity', max_length=7),
        ),
    ]
