# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-13 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_auto_20200313_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('target_date', models.DateTimeField(blank=True, null=True)),
                ('money_target', models.IntegerField(blank=True, null=True)),
                ('money_raised', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Org')),
            ],
        ),
    ]
