# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-16 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0002_auto_20200413_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='money_raised',
            field=models.IntegerField(default=0),
        ),
    ]
