# Generated by Django 3.0.5 on 2020-04-17 00:11

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('appeals', '0003_auto_20200416_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
