# Generated by Django 3.0.5 on 2020-04-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0005_auto_20200419_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
