# Generated by Django 3.0.5 on 2020-05-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0006_appeal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='money_target',
            field=models.IntegerField(default=0),
        ),
    ]
